GET http://localhost:3333/api/alunos

###
GET http://localhost:3333/api/alunos/22

###
POST http://localhost:3333/api/alunos
Content-Type: application/json

{
  "nome": "Violito",
  "sobrenome": "Prantos",
  "data_nascimento": "2003-07-10T03:00:00.000Z",
  "endereco": "Rua do Ingá, 811",
  "email": "prantos@gmail.com",
  "celular": "16911915245"
}

###
PUT http://localhost:3333/api/alunos/22
Content-Type: application/json

{
  "nome": "Violito",
  "sobrenome": "Prantos",
  "data_nascimento": "2003-07-10T03:00:00.000Z",
  "endereco": "Rua do Morumba, 203",
  "email": "pranto@gmail.com",
  "celular": "16911915245"
}
###
DELETE http://localhost:3333/api/alunos/22